### ISSUE TITLE
Writing Gold and Gearbits?

### ISSUE THREAD

**Issue by Failinhearts** [hegyak/SkyEditGUI#3]
I first off want to say, THANK YOU for creating a Skylanders Editor with a clear, easy to use interface. It's a godsend for diehard fans like me who have so many figures and not enough time to max them out.

When testing out the software however, it seems like Gold values are not properly saved to my figure, nor is Gearbits to my vehicles.

I'm looking to unlock all of the cosmetics from the Boom 5000, and that requires a lot of Gearbits. Am I doing something wrong, or is this feature still in development?

**Comment by hegyak** [comment]
Hello,
The Shield, GearBits and Weapons Level are not being written yet by the editor.  Nor, are they being read in yet.  I will try and get that done soon-ish.  I need to get a Dump of a Vehicle with data set so I can determine how the Values are supposed to be written on the Figure.

See https://github.com/hegyak/SkyEditGUI/issues/1

For questions I have about SuperCharger Figures.

Edit:
I wanted to add, Gold Values are not being written correctly?  That, I can look into ASAP.  What Figure are you attempting to Write to?

**Comment by hegyak** [comment]
After doing some testing, I found that Portal Writing is NOT working as of Alpha 5.  But Writing to a File works.  So, Alpha 6 will be delayed while I do a full refactoring and fix the Portal Writing Functionality.  On the positive, it will be more clean and clearly written code for both Reading and Writing of Figures for both Files and Portals.

**Comment by hegyak** [comment]
This has been resolved in Alpha 6:
https://github.com/hegyak/SkyEditGUI/releases/tag/Alpha-6

**Comment by zephyrUkon** [comment]
Amazing editor. But most of my figures were created using Cemu and the other save editor I use won't let me edit the files unless I play with them for a certain amount of time. I was wondering if you could add the ability to edit the digital files without the requirement of playing as the figure for a certain amount of time.
