### ISSUE TITLE
Works, but not much?

### ISSUE THREAD

**Issue by JarieSuisen** [hegyak/SkyEditGUI#4]
So, first off, super excited to see this develop!

But my issue is, when trying it out, I first tried my Xbox One Trap Team Portal, but even though my computer shows it, and claims working drivers, the program said it couldn't see it. So I tried my Wii wireless portal, and it seemed to work, but everything I read the program declared to be a Whirlwind...? Not sure if I'm missing a step in setup or something.

**Comment by hegyak** [comment]
The Wireless Portal, is a bit of a Unique thing.  The Protocol the program is using, was not setup for that.  I would need to look into what the Wireless Portal needs Vs. a Wired Portal.  It shouldn't be too hard to figure that out.  Hopefully.  And, I would also need a way to identify a Wireless Portal Vs. a Wired Portal.

I don't have an Xbox One Portal to work with myself.  I do not know if that portal works like other Wired Portals.

The program should recognize/see whatever Figure you put onto the Portal and only require that the Portal is connected to your Windows System.  The Program is a single Executable file.

If the program is defaulting to Whirlwind, then it may be seeing the Generation/Variant ID Bytes but not the Figure's ID Bytes.  Which, should not happen normally.

What Figure(s) are you trying to load?  I know the Generation 6 Figures, are, not perfectly identified yet.  That is still a work in progress.

**Comment by hegyak** [comment]
After doing some testing, I found that Portal Writing is NOT working as of Alpha 5. But Writing to a File works. So, Alpha 6 will be delayed while I do a full refactoring and fix the Portal Writing Functionality. On the positive, it will be more clean and clearly written code for both Reading and Writing of Figures for both Files and Portals.

**Comment by hegyak** [comment]
Portal Reading and Writing has been fixed in Alpha 6
https://github.com/hegyak/SkyEditGUI/releases/tag/Alpha-6
